spring.application.name=api-bank

# Define o perfil padrão como "local" se nenhuma variável for passada
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# O Flyway cria as tabelas e gerencia a estrutura
spring.flyway.enabled=true

# O Hibernate apenas valida se as entidades Java batem com o banco
spring.jpa.hibernate.ddl-auto=validate